# Generated by Django 4.0.4 on 2022-05-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
